# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: OnPush (Build and Publish)
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore TrelloDotNet.sln
      working-directory: TrelloDotNet
    - name: Build
      run: dotnet build --configuration Release --no-restore
      working-directory: TrelloDotNet
    - name: SetUserSecretsTrelloApiKey        
      run: dotnet user-secrets set TrelloApiKey ${{ secrets.TRELLOAPIKEY }} --project TrelloDotNet/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj
    - name: SetUserSecretsTrelloToken        
      run: dotnet user-secrets set TrelloToken ${{ secrets.TRELLOTOKEN }} --project TrelloDotNet/TrelloDotNet.Tests/TrelloDotNet.Tests.csproj      
    - name: Test      
      run: dotnet test --configuration Release --no-build --verbosity normal
      working-directory: TrelloDotNet/TrelloDotNet.Tests
    - name: Publish 
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
