# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: OnPush (Build and Publish)
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 6.0.x
    - name: SetUserSecrets        
      run: dotnet user-secrets set TrelloApiKey ${{ secrets.TRELLOAPIKEY }} --project TrelloDotNet.Tests.csproj
    - name: Restore dependencies
      run: dotnet restore TrelloDotNet.sln
      working-directory: TrelloDotNet
    - name: Build
      run: dotnet build --no-restore
      working-directory: TrelloDotNet
    - name: Test      
      env:
        TrelloApiKey: ${{ secrets.TRELLOAPIKEY }}
        TrelloToken: ${{ secrets.TRELLOTOKEN }}
      run: dotnet test --no-build --verbosity normal
      working-directory: TrelloDotNet
    - name: Publish 
      run: nuget push **\*.nupkg -Source 'https://api.nuget.org/v3/index.json' -ApiKey ${{secrets.NUGET_API_KEY}} -SkipDuplicate
